# Generated by Django 5.2.10 on 2026-02-02 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='horas_academicas',
            field=models.PositiveIntegerField(default=2, verbose_name='Horas Académicas'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora'),
        ),
    ]
