# Generated by Django 5.2.10 on 2026-02-02 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_alter_asistencia_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilestudiante',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de Teléfono'),
        ),
    ]
