# Generated by Django 5.2.10 on 2026-02-02 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_perfilestudiante_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilestudiante',
            name='telefono',
            field=models.CharField(max_length=20, verbose_name='Número de Teléfono'),
        ),
    ]
